/* ============================================================
   ADEPTIO · STAFF persona (ESS) — ochre
   Web: My day · Time · Requests(→new→detail) · Payslips(→detail)
        · Documents · Me
   Mobile: Home · Time · Requests · Me (+ drill screens)
   ============================================================ */
(function () {
  const { icon, kpi, card, badge, idtag, rowitem, rowlist, table, steps, empty, avatar, sparkline, heatcal, kip } = UI;

  const statusBadge = (r) => badge(r.status);

  /* v2.3.2.db — acting-user picker: ANY row of db_people can drive this lens.
     New hires appear here the moment HR creates them. */
  function userPicker() {
    const cur = DATA.me.staff.id;
    return `<select class="input sm staff-pick" title="Demo — act as any user from db_people" aria-label="Acting staff user">
      ${DATA.employees.map(e => `<option value="${e.id}" ${e.id === cur ? "selected" : ""}>${e.name} · ${e.id}</option>`).join("")}</select>`;
  }
  function userPickerCard() {
    return card("Acting as — pick a user from db_people", `
      ${userPicker()}
      <p class="small muted" style="margin-top:10px">${DATA.me.staff.status === "probation" ? `<span class="badge warn plain">probation</span> ` : ""}Every Staff screen — requests, payslips, punches, documents, KPIs — re-reads the selected user's rows from the split stores. Hire someone in HR → People and they're selectable here immediately.</p>`, { icon: "user" });
  }

  /* ---------- shared fragments ---------- */
  function requestRows(device) {
    return rowlist(DATA.mine().map(r => rowitem({
      icon: { Leave: "calendar", Overtime: "clock", Claim: "receipt", Correction: "edit" }[r.type],
      title: `${r.detail}`,
      sub: `${r.id} · ${r.dates} · ${r.stage}`,
      side: statusBadge(r),
      go: `staff/${device}/request-detail/${r.id}`
    })));
  }

  function clockCard() {
    const s = DATA.state;
    return `<div class="clock-hero">
      <div class="ch-line">
        <div>
          <div class="ch-sub">${s.clockedIn ? "Clocked in · " + s.clockIn : "Not clocked in"}</div>
          <div class="ch-time">08:31<span style="font-size:15px;opacity:.7"> AM</span></div>
        </div>
        <button class="ch-btn" data-act="clock">${icon(s.clockedIn ? "logout" : "clock")} ${s.clockedIn ? "Clock out" : "Clock in"}</button>
      </div>
      <div class="geo">${icon("pin")} Vientiane Plant 1 · inside geofence · GPS ✓</div>
    </div>`;
  }

  function alertsList(device) {
    const m = device === "mobile";
    const ps = DATA.myPayslips()[0]; // acting user's latest slip, if any
    const payGo = ps ? (m ? "staff/mobile/payslip/" + ps.id : "staff/web/payslips") : (m ? "staff/mobile/me" : "staff/web/payslips");
    const docGo = m ? "staff/mobile/me" : "staff/web/documents";
    const vault = DATA.has("vault");
    return rowlist([
      ps ? rowitem({ icon: "banknote", title: `Payslip for ${ps.period.split(" ")[0]} is ready`, sub: "Net " + kip(ps.net) + " · published " + ps.paid, side: badge("ok"), go: payGo })
         : rowitem({ icon: "banknote", title: "First payslip arrives with the next pay run", sub: "PR-2026-06 · cutoff Jun 25", side: `<span class="badge plain">Upcoming</span>`, neutral: 1, go: payGo }),
      rowitem({ icon: "megaphone", title: "Town hall — Friday 14:00", sub: "Announcement · canteen, Plant 1", side: `<span class="badge plain">In-app</span>`, neutral: 1 }),
      vault
        ? rowitem({ icon: "shield", title: "Acknowledge Code of conduct v4", sub: "Due Jun 20 · 2 min read", side: badge("pending"), go: docGo })
        : `<div class="rowitem row-locked"><span class="ric n">${icon("lock")}</span><div class="rmain"><div class="rt">Policy acknowledgements & doc-expiry alerts</div><div class="rs">Documents Vault</div></div><div class="rside">${UI.lockTag(DATA.unlockLabel("vault"))}</div></div>`
    ]);
  }

  function payslipDetailBody(id, device) {
    const p = DATA.payslips.find(x => x.id === id) || DATA.payslips[0];
    const rows = p.lines.map(l => ({ cells: [l[0], `<span class="num">${kip(l[1])}</span>`] }))
      .concat(p.deds.map(l => ({ cells: [l[0], `<span class="num" style="color:var(--bad)">− ${kip(-l[1])}</span>`] })));
    return `
      <div class="grid cols-3">
        ${kpi("Net pay", `<span class="num">${kip(p.net)}</span>`, `Paid ${p.paid} · BCEL ··4821`, { hero: 1 })}
        ${kpi("Gross", kip(p.gross), "Before tax & SSO")}
        ${kpi("Deductions", kip(p.gross - p.net), "PIT + social security")}
      </div>
      ${card("Earnings & deductions — " + p.period, table(
        [{ h: "Pay code" }, { h: "Amount", r: 1 }], rows
      ) + `<hr class="hr-sep"><div style="display:flex;justify-content:space-between;font-weight:800;font-size:13.5px;padding:0 12px"><span>Net pay</span><span class="num">${kip(p.net)}</span></div>`, { icon: "banknote" })}
      ${card("About this payslip", `<p class="small muted">Generated by pay run ${idtag("PR-" + p.id.slice(3))} from the payroll cell · PIT and social security follow the Lao statutory pack · serialized ${idtag(p.id)} and audit-logged. Tax & SSO breakdown is itemised above — one ledger line per pay code.</p>`, { icon: "shield" })}`;
  }

  /* ---------- WEB screens ---------- */
  const web = {
    home() {
      const m = DATA.me.staff;
      return {
        title: "Good morning, " + m.name.split(" ")[0], sub: `Wednesday, June 10 2026 · ${m.role} · everything that needs you, in one place.`,
        actions: `${userPicker()}<button class="btn soft" data-go="staff/web/requests">${icon("plus")} New request</button>`,
        body: `
        <div class="grid cols-3">
          <div class="span-2" style="display:flex;flex-direction:column;gap:16px">
            ${clockCard()}
            <div class="grid cols-2">
              ${card("Alerts & actions", alertsList("web"), { icon: "bell", badge: badge("pending") })}
              ${card("My requests", requestRows("web"), { icon: "inbox", link: "staff/web/requests" })}
            </div>
          </div>
          <div style="display:flex;flex-direction:column;gap:16px">
            ${card("My month", heatcal({ until: 10, levels: { 4: "bad" } }) + `<div class="legend" style="margin-top:12px"><span><i style="background:var(--acc-ln)"></i>Present</span><span><i style="background:var(--bad-bg)"></i>Absence</span><span><i style="background:var(--line-2)"></i>Upcoming</span></div>`, { icon: "calendar" })}
            ${card("My KPIs", `
              <div class="rowlist">
                ${rowitem({ icon: "check", title: "Attendance", sub: "Trailing 90 days", side: `<b class="num">${m.attend}%</b>` })}
                ${rowitem({ icon: "clock", title: "Punctuality", sub: "On-time arrivals", side: `<b class="num">96%</b>` })}
                ${rowitem({ icon: "sun", title: "Leave balance", sub: "Annual remaining", side: `<b class="num">${m.leaveBal} d</b>` })}
                ${rowitem({ icon: "sparkle", title: "Training", sub: "Safety track", side: `<b class="num">80%</b>` })}
              </div>`, { icon: "pulse" })}
          </div>
        </div>
        ${card(t("common.quickActions"), `
          <div class="choice-row">
            <button class="choice" data-act="clock">${icon("clock")} Clock in / out</button>
            <button class="choice" data-go="staff/web/request-new/Leave">${icon("calendar")} Request leave</button>
            <button class="choice" data-go="staff/web/request-new/Claim">${icon("receipt")} Submit claim</button>
            <button class="choice" data-go="staff/web/payslips">${icon("banknote")} View payslip</button>
            ${DATA.has("docRequests") ? `<button class="choice" data-go="staff/web/documents">${icon("file")} Request document</button>` : UI.lockChoice("Request document", DATA.unlockLabel("docRequests"))}
          </div>`, { icon: "sparkle" })}`
      };
    },

    time() {
      return {
        title: "Time & attendance", sub: "Your punches, this month and history — corrections go through the TC flow.",
        actions: `<button class="btn soft" data-go="staff/web/request-new/Correction">${icon("edit")} Request correction</button>`,
        body: `
        <div class="grid cols-3">
          <div class="span-2" style="display:flex;flex-direction:column;gap:16px">
            ${clockCard()}
            ${card("Today — Wednesday, Jun 10", rowlist([
          rowitem({ icon: "check", title: "Clock in — 08:30", sub: "Mobile · GPS inside geofence", side: badge("ok") }),
          rowitem({ icon: "sun", title: "Lunch — 12:00 to 13:00", sub: "Auto break · unpaid", side: `<span class="badge plain">Scheduled</span>`, neutral: 1 }),
          rowitem({ icon: "clock", title: "Expected out — 17:30", sub: "Shift A · 8h standard", side: `<span class="badge plain">Upcoming</span>`, neutral: 1 })
        ]), { icon: "clock" })}
            ${card("Punch history", table(
          [{ h: "Date" }, { h: "In" }, { h: "Out" }, { h: "Hours", r: 1 }, { h: "Status", r: 1 }],
          [
            { cells: ["Tue, Jun 09", "08:28", "17:32", `<span class="num">8.1</span>`, badge("ok")] },
            { cells: ["Mon, Jun 08", "08:31", "17:30", `<span class="num">8.0</span>`, badge("ok")] },
            { cells: ["Fri, Jun 05", "—", "17:31", `<span class="num">—</span>`, badge("flagged")] },
            { cells: ["Thu, Jun 04", "08:29", "19:40", `<span class="num">10.2</span>`, `<span class="badge acc">OT +2h</span>`] },
            { cells: ["Wed, Jun 03", "08:30", "17:29", `<span class="num">8.0</span>`, badge("ok")] }
          ]), { icon: "history" })}
          </div>
          <div style="display:flex;flex-direction:column;gap:16px">
            ${card("June 2026", heatcal({ until: 10, levels: { 4: "l3", 5: "bad" } }), { icon: "calendar" })}
            ${card("Exception", rowlist([rowitem({ icon: "alert", title: "Missing punch — Jun 05", sub: "No clock-in recorded · fix via correction", side: `<button class="btn xs soft" data-go="staff/web/request-new/Correction">Fix</button>` })]), { icon: "alert" })}
            ${card("This month", `<div style="display:flex;align-items:center;gap:16px">${UI.donut(98)}<div class="small muted">Worked <b class="num" style="color:var(--ink)">62.3h</b> of 63.5h scheduled<br>OT approved · <b class="num" style="color:var(--ink)">4h</b></div></div>`, { icon: "pulse" })}
          </div>
        </div>`
      };
    },

    requests() {
      const mine = DATA.mine();
      const n = (s) => String(mine.filter(r => r.status === s).length);
      return {
        title: "My requests", sub: "Leave, overtime, claims and corrections — one inbox, traceable IDs, every status visible.",
        actions: `<button class="btn" data-go="staff/web/request-new/Leave">${icon("plus")} New request</button>`,
        body: `
        <div class="grid cols-4">
          ${kpi("Open", n("pending"), "Awaiting approval")}
          ${kpi("Approved", n("approved"), "Last 30 days")}
          ${kpi("Returned", n("returned"), "Needs your edit")}
          ${kpi("Leave balance", DATA.me.staff.leaveBal + " d", "Annual · accrues 1.25/mo")}
        </div>
        ${card("All requests", `
          <div class="choice-row" style="margin-bottom:12px">
            <button class="choice" aria-pressed="true">${t("common.all")}</button>
            <button class="choice">Leave</button><button class="choice">Overtime</button>
            <button class="choice">Claims</button><button class="choice">Corrections</button>
          </div>` + requestRows("web"), { icon: "inbox" })}`
      };
    },

    "request-new"(param) {
      const type = param || "Leave";
      const pressed = (x) => type === x ? 'aria-pressed="true"' : "";
      return {
        title: "New request", sub: "Submits into the Requests & Approvals cell — L1 manager, then L2 HR where the chain requires it.",
        crumbs: [{ label: "Requests", go: "staff/web/requests" }, { label: "New" }],
        body: `
        <div class="grid cols-3">
          <div class="card span-2">
            <div class="field"><label>Request type</label>
              <div class="choice-row">
                <button class="choice" ${pressed("Leave")} data-go="staff/web/request-new/Leave">${icon("calendar")} Leave</button>
                <button class="choice" ${pressed("Overtime")} data-go="staff/web/request-new/Overtime">${icon("clock")} Overtime</button>
                <button class="choice" ${pressed("Claim")} data-go="staff/web/request-new/Claim">${icon("receipt")} Claim</button>
                <button class="choice" ${pressed("Correction")} data-go="staff/web/request-new/Correction">${icon("edit")} Correction</button>
              </div>
            </div>
            <div class="grid cols-2">
              <div class="field"><label>${type === "Claim" ? "Amount (₭)" : "From"}</label><input class="input" value="${type === "Claim" ? "420,000" : "Jun 18, 2026"}"></div>
              <div class="field"><label>${type === "Claim" ? "Receipt date" : "To"}</label><input class="input" value="${type === "Claim" ? "Jun 06, 2026" : "Jun 19, 2026"}"></div>
            </div>
            ${type === "Leave" ? `<div class="field"><label>Leave type</label><select class="input"><option>Annual leave</option><option>Sick leave</option><option>Personal leave</option><option>Statutory</option></select><span class="hint">Balance after request: 10 days</span></div>` : ""}
            <div class="field"><label>Reason / note</label><textarea class="input" placeholder="A short note for your approver…"></textarea></div>
            <div class="field"><label>Attachment</label><button class="btn ghost sm">${icon("plus")} Add file or receipt photo</button></div>
            <div style="display:flex;gap:9px;justify-content:flex-end">
              <button class="btn ghost" data-go="staff/web/requests">${t("common.cancel")}</button>
              <button class="btn" data-act="submit-request:${type}">${icon("send")} ${t("common.submit")} request</button>
            </div>
          </div>
          <div style="display:flex;flex-direction:column;gap:16px">
            ${card("Approval chain", steps([{ t: "You", s: "Submit" }, { t: "Khamla S.", s: "L1 · Manager" }, ...(type === "Claim" && DATA.has("l2") ? [{ t: "HR / Finance", s: "L2 · Settle" }] : [{ t: "HR", s: "Record & sync" }])], 0) + (DATA.has("l2") ? "" : `<p class="small muted" style="margin-top:10px">${icon("lock", "lk")} Single-step on Essential — multi-step chains (L1 → L2) arrive at ${DATA.unlockLabel("l2")}.</p>`), { icon: "layers" })}
            ${card("Good to know", `<p class="small muted">${type === "Leave" ? "Your manager sees the team conflict calendar before approving. Approved leave syncs to payroll automatically." : type === "Claim" ? "Claims are validated by your manager, then settled by HR/Finance through payroll or finance export." : type === "Overtime" ? "OT is checked against schedule and rate caps in the payroll cell." : "Corrections adjust the attendance ledger — the change is audit-logged and pay re-derives."}</p>`, { icon: "sparkle" })}
          </div>
        </div>`
      };
    },

    "request-detail"(id) {
      const r = DATA.requests.find(x => x.id === id) || DATA.requests[0];
      const stepIdx = r.status === "approved" ? 3 : r.status === "returned" ? 1 : (r.stage.startsWith("L2") ? 2 : 1);
      return {
        title: r.detail, sub: `Submitted ${r.submitted} · shared ID traces this item across every persona lens.`,
        crumbs: [{ label: "Requests", go: "staff/web/requests" }, { label: r.id }],
        actions: `${idtag(r.id)} ${statusBadge(r)}`,
        body: `
        <div class="grid cols-3">
          <div class="span-2" style="display:flex;flex-direction:column;gap:16px">
            ${card("Where it is", steps([
          { t: "Submitted", s: r.submitted }, { t: "Manager · L1", s: "Khamla S." },
          ...(r.type === "Claim" && DATA.has("l2") ? [{ t: "HR / Finance · L2", s: "Settle via payroll" }] : [{ t: "HR", s: "Record & sync" }]),
          { t: "Done", s: "Ledger updated" }
        ], stepIdx), { icon: "layers" })}
            ${card("Details", table([{ h: "Field" }, { h: "Value" }], [
          { cells: ["Type", r.type] }, { cells: ["Dates", r.dates] },
          { cells: ["Note", r.note] }, { cells: ["Stage", r.stage] },
          { cells: ["SLA", r.sla] }
        ]), { icon: "file" })}
          </div>
          <div style="display:flex;flex-direction:column;gap:16px">
            ${card("Actions", `<div style="display:flex;flex-direction:column;gap:8px">
              ${r.status === "pending" ? `<button class="btn ghost">${icon("x")} Cancel request</button>` : ""}
              ${r.status === "returned" ? `<button class="btn" data-go="staff/web/request-new/${r.type}">${icon("edit")} Edit & resubmit</button>` : ""}
              <button class="btn ghost" data-act="export:reqhistory">${icon("download")} Export history</button>
            </div>`, { icon: "settings" })}
            ${card("One ledger, many lenses", `<p class="small muted">Your manager sees ${idtag(r.id)} in the L1 queue; HR sees it in cross-module approvals; the CEO only ever sees it inside aggregates. Approve it in the Manager persona and watch this page update.</p>`, { icon: "refresh" })}
          </div>
        </div>`
      };
    },

    payslips() {
      const mine = DATA.myPayslips(); // v2.3.2.db — slips of the ACTING user only
      const p = mine[0];
      if (!p) return {
        title: "Payslips", sub: "Self-serve slips with tax and social security breakdown — published by each pay run.",
        actions: userPicker(),
        body: `
        ${card("", empty("banknote", "No payslips yet for " + DATA.me.staff.name.split(" ")[0], "The first pay run after hire publishes here — payroll reads the db_people row this user just got."))}
        ${card("How slips arrive", `<p class="small muted">Pay run ${idtag("PR-2026-06")} (HR → Payroll) generates one serialized slip per active employee at disbursement. New hires join the next cutoff automatically — their master record is already in db_people.</p>`, { icon: "sparkle" })}`
      };
      return {
        title: "Payslips", sub: "Self-serve slips with tax and social security breakdown — published by each pay run.",
        actions: userPicker(),
        body: `
        <div class="grid cols-3">
          <div class="card tinted span-2">
            <div class="card-head"><span class="t">${icon("banknote")} Latest — ${p.period}</span>${badge("ok")}</div>
            <div style="display:flex;align-items:flex-end;justify-content:space-between;gap:16px;flex-wrap:wrap">
              <div><div class="eyebrow">Net pay</div>
              <div class="num" style="font-family:var(--display);font-size:38px;font-weight:550;letter-spacing:-.03em">${kip(p.net)}</div>
              <div class="small muted">Paid ${p.paid} · BCEL ··4821</div></div>
              <div style="display:flex;gap:8px"><button class="btn" data-go="staff/web/payslip/${p.id}">${icon("eye")} View</button>
              <button class="btn ghost" data-act="export:payslip">${icon("download")} PDF</button></div>
            </div>
          </div>
          ${card("Year to date", rowlist([
          rowitem({ icon: "banknote", title: "Net paid 2026", sub: "Jan – May", side: `<b class="num">₭ 23.9M</b>` }),
          rowitem({ icon: "shield", title: "PIT withheld", sub: "Personal income tax", side: `<b class="num">₭ 2.21M</b>` }),
          rowitem({ icon: "heart", title: "Social security", sub: "Employee 5.5%", side: `<b class="num">₭ 1.47M</b>` })
        ]), { icon: "pulse" })}
        </div>
        ${card("History", table(
          [{ h: "Period" }, { h: "ID" }, { h: "Gross", r: 1 }, { h: "Net", r: 1 }, { h: "", r: 1 }],
          mine.map(s => ({
            go: `staff/web/payslip/${s.id}`,
            cells: [s.period, idtag(s.id), `<span class="num">${kip(s.gross)}</span>`, `<b class="num">${kip(s.net)}</b>`, icon("chevR")]
          }))), { icon: "history" })}`
      };
    },

    payslip(id) {
      const p = DATA.payslips.find(x => x.id === id) || DATA.payslips[0];
      return {
        title: "Payslip — " + p.period, sub: "One ledger line per pay code · statutory items computed by the localizable rules pack.",
        crumbs: [{ label: "Payslips", go: "staff/web/payslips" }, { label: p.id }],
        actions: `<button class="btn ghost" data-act="export:payslip">${icon("download")} PDF</button><button class="btn ghost" data-act="export:tax">${icon("file")} Tax statement</button>`,
        body: payslipDetailBody(id, "web")
      };
    },

    documents() {
      return {
        title: "Documents", sub: "Your vault — personal documents with expiry alerts, policies to acknowledge, and self-serve requests.",
        body: `
        <div class="grid cols-2">
          ${card("My documents", (DATA.myDocs().filter(d => d.kind !== "Policy").length
          ? rowlist(DATA.myDocs().filter(d => d.kind !== "Policy").map(d => rowitem({
            icon: "file", title: d.name, sub: `${d.kind} · expires ${d.expiry}`, side: badge(d.status)
          })))
          : empty("folder", "No documents on file yet", "HR uploads contracts & IDs at onboarding — request one below.")), { icon: "folder" })}
          ${card("Policies to acknowledge", rowlist([
          rowitem({ icon: "shield", title: "Code of conduct v4", sub: "Published Jun 02 · due Jun 20", side: `<button class="btn xs" data-act="wf-ack-policy">Acknowledge</button>` }),
          rowitem({ icon: "shield", title: "Safety handbook v7", sub: "Acknowledged May 12", side: badge("ok") })
        ]), { icon: "check" })}
        </div>
        ${card("Request a document", `
          <p class="small muted" style="margin-bottom:12px">Generated from System-Admin templates with serial number + e-signature (flow J · DOC-####). Self-service where policy allows.</p>
          <div class="choice-row">
            <button class="choice" data-act="gen-doc:staff-salary">${icon("banknote")} Salary certificate</button>
            <button class="choice" data-act="gen-doc:staff-employment">${icon("check")} Employment verification</button>
            <button class="choice" data-act="gen-doc:staff-attendance">${icon("calendar")} Attendance record</button>
          </div>`, { icon: "send" })}`
      };
    },

    /* ---------- v2.3.2.db — my slice of the split stores ---------- */
    mydata() {
      const m = DATA.me.staff;
      return {
        title: "My data", sub: "Exactly which stores hold your records — your own slice, addable & deletable where policy allows. Scope enforced by the kernel.",
        actions: `<button class="btn ghost" data-act="export:mydata">${icon("download")} Export my data</button>`,
        body: `
        <div class="grid cols-3">
          <div class="span-2" style="display:flex;flex-direction:column;gap:16px">
            ${card("My requests — db_workflow (delete = withdraw while pending)", DBV.tableEditor("db_workflow", "requests", { filter: r => r.who === m.name, canAdd: false }) + `<div style="margin-top:10px"><button class="btn sm soft" data-go="staff/web/request-new/Leave">${icon("plus")} New request (through the cell API)</button></div>`, { icon: "inbox" })}
            ${DATA.has("vault")
              ? card("My documents — db_docs (metadata; files live in L-CU)", DBV.tableEditor("db_docs", "documents", { filter: d => d.emp === m.id }), { icon: "folder" })
              : card("My documents — db_docs", `<div class="rowitem row-locked"><span class="ric n">${icon("lock")}</span><div class="rmain"><div class="rt">Documents Vault store is not provisioned on Essential</div><div class="rs">Provisioned lazily — flags decide which stores exist (§02)</div></div><div class="rside">${UI.lockTag(DATA.unlockLabel("vault"))}</div></div>`, { icon: "folder" })}
            ${card("My punches — db_time (corrections go through the TC flow, not edits)", DBV.tableEditor("db_time", "punches", { filter: p => p.emp === m.id, canAdd: false, canDel: false }), { icon: "clock" })}
          </div>
          <div style="display:flex;flex-direction:column;gap:16px">
            ${card("Where my data lives", DBV.storeGrid(null, ["db_people", "db_time", "db_workflow", "db_payroll", "db_docs"]), { icon: "layers" })}
            ${card("Isolation, by design", `<p class="small muted">Your rows live in <b>${DB.TENANT}</b>'s own physical stores — one small database per tenant × store. Offboarding is an export + delete of actual files; cross-tenant exposure is structurally impossible, not policy-prevented.</p>`, { icon: "shield" })}
          </div>
        </div>`
      };
    },

    /* ---------- v2.3.2.db — my reports (runs + file storage) ---------- */
    reports() {
      return {
        title: "My reports", sub: "Statements over your own rows only — each section keeps its last 3 runs; click a run to view (read-only) or download. Older runs move to file storage.",
        actions: `${userPicker()}<button class="btn ghost" data-go="staff/web/report-files">${icon("folder")} File storage</button>`,
        body: REP.library("staff", "staff/web")
      };
    },
    "report-run"(param) {
      const p = REP.runPage(param, "staff", "staff/web");
      return {
        title: p.title, sub: p.sub,
        crumbs: [{ label: "My reports", go: "staff/web/reports" }, { label: p.run ? p.run.id : "run" }],
        actions: p.run ? `${idtag(p.run.id)} ${p.run.archived ? `<span class="badge plain">archived</span>` : `<span class="badge ok plain">recent</span>`}` : "",
        body: p.body
      };
    },
    "report-files"() {
      const f = REP.filesPage("staff", "staff/web");
      return {
        title: "Report file storage", sub: "Runs older than the last 3 live here — one folder per report, view-only with download links.",
        crumbs: [{ label: "My reports", go: "staff/web/reports" }, { label: "File storage" }],
        body: f.kpis + f.folders
      };
    },

    me() {
      const m = DATA.me.staff;
      return {
        title: "My profile", sub: "Own-slice edits — sensitive changes route through an approval, everything is audit-logged.",
        actions: `<button class="btn soft" data-act="wf-profile-request">${icon("edit")} Request change</button>`,
        body: `
        <div class="grid cols-3">
          <div class="card span-2">
            <div style="display:flex;align-items:center;gap:14px;margin-bottom:16px">${avatar(m.name, 1)}
              <div><div style="font-weight:800;font-size:16px">${m.name}</div>
              <div class="small muted">${m.role} · ${idtag(m.id)}</div></div></div>
            ${table([{ h: "Field" }, { h: "Value" }], [
          { cells: ["Division", m.div + (m.team !== "—" ? " · " + m.team : "")] },
          { cells: ["Site", m.site] },
          { cells: ["Employment", `Full-time · since ${m.since}${m.status === "probation" ? ` · <span class="badge warn plain">probation</span>` : ""}`] },
          { cells: ["Phone", "+856 20 ·· ·· 482"] },
          { cells: ["Bank", "BCEL ····4821"] },
          { cells: ["Emergency contact", "Vanh P. · +856 20 ·· ·· 110"] }
        ])}
          </div>
          <div style="display:flex;flex-direction:column;gap:16px">
            ${userPickerCard()}
            ${card("Language", `<div class="choice-row"><button class="choice" aria-pressed="true">English</button><button class="choice" data-act="lang-lo">ລາວ</button></div><p class="small muted" style="margin-top:10px">Bilingual UI is a platform feature — the Lao pack is staged for the build phase.</p>`, { icon: "globe" })}
            ${card("My access", `<p class="small muted">Persona <b style="color:var(--acc-d)">Staff · ESS</b> — create &amp; edit own data, submit requests. Scope enforced by the kernel on every call.</p>`, { icon: "lock" })}
          </div>
        </div>`
      };
    }
  };

  /* ---------- MOBILE tabs + drills ---------- */
  const mobile = {
    home() {
      return {
        title: "My day", body: `
        ${clockCard()}
        <div class="grid cols-2">
          ${kpi("Leave", DATA.me.staff.leaveBal + " d", "balance")}
          ${kpi("Requests", String(DATA.mine().filter(r => r.status === "pending").length), "open")}
        </div>
        ${card("Alerts", alertsList("mobile"), { icon: "bell" })}
        ${card("My requests", requestRows("mobile"), { icon: "inbox" })}
        ${card(t("common.quickActions"), `<div class="choice-row">
          <button class="choice" data-go="staff/mobile/request-new/Leave">${icon("calendar")} Leave</button>
          <button class="choice" data-go="staff/mobile/request-new/Claim">${icon("receipt")} Claim</button>
          <button class="choice" data-go="${DATA.myPayslips()[0] ? "staff/mobile/payslip/" + DATA.myPayslips()[0].id : "staff/mobile/me"}">${icon("banknote")} Payslip</button>
        </div>`, { icon: "sparkle" })}`
      };
    },
    time() {
      return {
        title: "Time", body: `
        ${clockCard()}
        ${card("June 2026", heatcal({ until: 10, levels: { 5: "bad" } }), { icon: "calendar" })}
        ${card("Recent", rowlist([
          rowitem({ icon: "check", title: "Jun 09 · 08:28 – 17:32", sub: "8.1 h · on time", side: badge("ok") }),
          rowitem({ icon: "alert", title: "Jun 05 · missing in", sub: "Fix via correction", side: `<button class="btn xs soft" data-go="staff/mobile/request-new/Correction">Fix</button>` }),
          rowitem({ icon: "check", title: "Jun 04 · 08:29 – 19:40", sub: "10.2 h · OT +2h", side: `<span class="badge acc">OT</span>` })
        ]), { icon: "history" })}`
      };
    },
    requests() {
      return {
        title: "Requests", body: `
        <button class="btn" style="width:100%" data-go="staff/mobile/request-new/Leave">${icon("plus")} New request</button>
        ${card("Mine", requestRows("mobile"), { icon: "inbox" })}`
      };
    },
    me() {
      const m = DATA.me.staff;
      return {
        title: "Me", body: `
        ${card("", `<div style="display:flex;align-items:center;gap:13px">${avatar(m.name, 1)}<div><div style="font-weight:800">${m.name}</div><div class="small muted">${m.role}</div></div></div>`)}
        ${card("Switch user — db_people", userPicker() + `<p class="small muted" style="margin-top:8px">New hires are selectable immediately.</p>`, { icon: "user" })}
        ${card("Payslips", (DATA.myPayslips().length
          ? rowlist(DATA.myPayslips().map(p => rowitem({ icon: "banknote", title: p.period, sub: "Net " + kip(p.net), side: icon("chevR"), go: `staff/mobile/payslip/${p.id}` })))
          : empty("banknote", "No payslips yet", "Published by the next pay run")), { icon: "banknote" })}
        ${card("Documents", (DATA.myDocs().length
          ? rowlist(DATA.myDocs().slice(0, 3).map(d => rowitem({ icon: "file", title: d.name, sub: d.kind + " · " + d.expiry, side: badge(d.status) })))
          : empty("folder", "No documents yet", "HR uploads at onboarding")), { icon: "folder" })}
        ${card("Language", `<div class="choice-row"><button class="choice" aria-pressed="true">EN</button><button class="choice" data-act="lang-lo">ລາວ</button></div>`, { icon: "globe" })}`
      };
    },
    "request-detail"(id) {
      const r = DATA.requests.find(x => x.id === id) || DATA.requests[0];
      const stepIdx = r.status === "approved" ? 3 : r.status === "returned" ? 1 : (r.stage.startsWith("L2") ? 2 : 1);
      return {
        title: r.id, back: "staff/mobile/requests", body: `
        ${card("", `<div style="display:flex;justify-content:space-between;align-items:center;gap:8px;flex-wrap:wrap">${idtag(r.id)}${statusBadge(r)}</div>
          <h3 style="font-size:16px;margin:10px 0 2px">${r.detail}</h3><div class="small muted">${r.dates}</div>`)}
        ${card("Progress", steps([{ t: "Submitted" }, { t: "L1 · Manager" }, { t: r.type === "Claim" && DATA.has("l2") ? "L2 · HR" : "HR record" }, { t: "Done" }], stepIdx), { icon: "layers" })}
        ${card("Note", `<p class="small">${r.note}</p>`, { icon: "file" })}`
      };
    },
    "request-new"(param) {
      const type = param || "Leave";
      return {
        title: "New " + type.toLowerCase(), back: "staff/mobile/requests", body: `
        ${card("", `
          <div class="field"><label>Type</label><div class="choice-row">
            ${["Leave", "Overtime", "Claim", "Correction"].map(x => `<button class="choice" ${x === type ? 'aria-pressed="true"' : ""} data-go="staff/mobile/request-new/${x}">${x}</button>`).join("")}
          </div></div>
          <div class="field"><label>${type === "Claim" ? "Amount (₭)" : "Dates"}</label><input class="input" value="${type === "Claim" ? "420,000" : "Jun 18 – 19"}"></div>
          <div class="field"><label>Note</label><textarea class="input" placeholder="Short note…"></textarea></div>
          <button class="btn" style="width:100%" data-act="submit-request:${type}">${icon("send")} Submit</button>`)}
        ${card("Chain", steps([{ t: "You" }, { t: "Manager" }, { t: type === "Claim" && DATA.has("l2") ? "HR/Fin" : "HR" }], 0), { icon: "layers" })}`
      };
    },
    payslip(id) {
      return { title: "Payslip", back: "staff/mobile/me", body: payslipDetailBody(id, "mobile") };
    }
  };

  /* ---------- v2.4.0.db.auth — My security (every persona gets it) ---------- */
  web.security = () => ({
    title: "My security", sub: "Your account behind the portal — change your password, see your sessions, revoke anything you don't recognize.",
    body: AUTHV.mySecurity("staff")
  });

  window.PERSONAS = window.PERSONAS || {};
  PERSONAS.staff = {
    key: "staff", label: t("personas.staff"), icon: "user",
    appName: "Adeptio Me", roleLine: "Employee Self-Service",
    domain: "app.adeptio.hr/me",
    nav: [
      { group: "Work", items: [
        { id: "home", icon: "home", label: t("staff.home") },
        { id: "time", icon: "clock", label: t("staff.time") },
        { id: "requests", icon: "inbox", label: t("staff.requests"), count: () => DATA.mine().filter(r => r.status === "pending").length }
      ]},
      { group: "Pay & docs", items: [
        { id: "payslips", icon: "banknote", label: t("staff.payslips") },
        { id: "documents", icon: "folder", label: t("staff.documents"), lock: "vault" },
        { id: "reports", icon: "chart", label: "My reports" }
      ]},
      { group: "Account", items: [
        { id: "me", icon: "user", label: t("staff.me") },
        { id: "security", icon: "shield", label: "My security" },
        { id: "mydata", icon: "layers", label: "My data" }
      ] }
    ],
    parent: { "request-new": "requests", "request-detail": "requests", "payslip": "payslips", "report-run": "reports", "report-files": "reports" },
    tabs: [
      { id: "home", icon: "home", label: "Home" },
      { id: "time", icon: "clock", label: "Time" },
      { id: "requests", icon: "inbox", label: "Requests" },
      { id: "me", icon: "user", label: "Me" }
    ],
    tabParent: { "request-detail": "requests", "request-new": "requests", "payslip": "me" },
    web, mobile
  };
})();
